//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliSource.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.SchoolClasses = new HashSet<SchoolClass>();
            this.Students = new HashSet<Student>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<SchoolClass> SchoolClasses { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
